pod 'AFNetworking', '~> 2.4.1'

   pod 'UMeng', '~> 2.2.1'
   pod 'UMengFeedback', '~> 1.4.2.1'

pod 'MBProgressHUD', '~> 0.9'

pod 'ASIHTTPRequest', '~> 1.8.2'

pod 'SDWebImage', '~> 3.7.1'


pod 'LBBlurredImage', '~> 0.2.0'


pod 'RTLabel', '~> 1.0'




